PLUGIN_NAME=		lens
PLUGIN_VERSION=		0.6
PLUGIN_REVISION=	3
PLUGIN_COMMENT=		Device-centric traffic insight and client management
PLUGIN_MAINTAINER=	claude@bxnny.de
PLUGIN_WWW=		https://github.com/BxnnyG/opnsense-lens

.include "../../Mk/plugins.mk"
